// TRADUCCIÓN DESHABILITADA TEMPORALMENTE - Solo chatbot activo
// import { ModelCoordinatorProvider } from "./components/ModelCoordinatorContext";
// import { TranslationProvider } from "./components/Translation/TranslationProvider";
// import LanguageSwitcher from "./components/Translation/LanguageSwitcher";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";

import ChatBotComponent from "./components/ChatBot/ChatBootComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* TRADUCCIÓN DESHABILITADA - Solo chatbot por ahora */}
        {/* <ModelCoordinatorProvider>
          <TranslationProvider> */}
        <div id="main-content">
          {children}
        </div>
        <ChatBotComponent />
        {/* <LanguageSwitcher /> */}
        {/* </TranslationProvider>
        </ModelCoordinatorProvider> */}
        <SpeedInsights />
      </body>
    </html>
  );
}
